#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/cgroupfs-mount" ]; then
		update-rc.d cgroupfs-mount defaults >/dev/null
		invoke-rc.d cgroupfs-mount start || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init/cgroupfs-mount.conf 1.4~ -- "$@"
# End automatically added section
