#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/newgen-xorg" ] ; then
	invoke-rc.d newgen-xorg stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'newgen-xorg.service' >/dev/null || true
fi
# End automatically added section
