#!/bin/sh
set -e

. /usr/share/debconf/confmodule

case "$1" in
  configure)
    logdir="/var/log/nginx"

    # Allow local admin to override
    if ! dpkg-statoverride --list "$logdir" >/dev/null; then
      chown root:adm $logdir
      chmod 0755 $logdir
    fi

    # Secure default logfiles on fresh installations
    if [ -z "$2" ]; then
      access_log="$logdir/access.log"
      error_log="$logdir/error.log"

      if [ ! -e "$access_log" ]; then
        touch "$access_log"
        chmod 640 "$access_log"
        chown www-data:adm "$access_log"
      fi

      if [ ! -e "$error_log" ]; then
        touch "$error_log"
        chmod 640 "$error_log"
        chown www-data:adm "$error_log"
      fi
    fi

    # If a symlink doesn't exist and can be created, then create it.
    if [ -z $2 ] && [ ! -e /etc/nginx/sites-enabled/default ] &&
       [ -d /etc/nginx/sites-enabled ] && [ -d /etc/nginx/sites-available ]; then
      ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
    fi

    # Create a default index page when not already present.
    if [ ! -e /var/www/html/index.nginx-debian.html ]; then
      mkdir -p /var/www/html
      cp /usr/share/nginx/html/index.html /var/www/html/index.nginx-debian.html
    fi

    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

# Automatically added by dh_installinit/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/nginx" ]; then
		update-rc.d nginx defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'nginx.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'nginx.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'nginx.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'nginx.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'nginx.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
