#!/bin/sh

set -e

case "${1}" in
    install)

        debconf-set-selections <<EOF
locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8
locales locales/default_environment_locale select en_US.UTF-8

keyboard-configuration	keyboard-configuration/modelcode	string	pc105
keyboard-configuration	keyboard-configuration/unsupported_options	boolean	true
keyboard-configuration	keyboard-configuration/altgr	select	The default for the keyboard layout
keyboard-configuration	keyboard-configuration/xkb-keymap	select	us
keyboard-configuration	keyboard-configuration/layout	select	English (US)
keyboard-configuration	keyboard-configuration/switch	select	No temporary switch
keyboard-configuration	keyboard-configuration/optionscode	string	nodeadkeys
keyboard-configuration	keyboard-configuration/unsupported_config_layout	boolean	true
keyboard-configuration	keyboard-configuration/compose	select	No compose key
keyboard-configuration	keyboard-configuration/variantcode	string
keyboard-configuration	keyboard-configuration/variant	select	English (US)
keyboard-configuration	keyboard-configuration/store_defaults_in_debconf_db	boolean	true
keyboard-configuration	keyboard-configuration/toggle	select	No toggling
keyboard-configuration	keyboard-configuration/unsupported_layout	boolean	true
keyboard-configuration	keyboard-configuration/unsupported_config_options	boolean	true
keyboard-configuration	keyboard-configuration/model	select	Generic 105-key PC (intl.)
keyboard-configuration	keyboard-configuration/layoutcode	string	us
keyboard-configuration	keyboard-configuration/ctrl_alt_bksp	boolean	false

rlx-user rlx-user/password password roche
rlx-user rlx-user/home string /opt/roche/home
rlx-user rlx-user/groups string sudo,video,dialout
rlx-user rlx-user/uid string
rlx-user rlx-user/gid string
rlx-user rlx-user/name string roche
rlx-user rlx-user/login-shell string
EOF
        ;;

    upgrade)
        ;;

    abort-upgrade)
        ;;
    *)
        echo "preinst called with unknown argument (${1})"
        exit 1
        ;;
esac

exit 0
