#!/bin/sh

# generate security key file (rsrkey.data) for RSR JWT
#
# example:
# {
#   "Key": "Some generated key"
# }
#

echo "Generating RSR key ..."
rsr_key_file=/opt/roche/var/lib/mollab/private/ui-api/rsr/rsrkey.data
new_key=$(tr -dc A-Za-z0-9 </dev/urandom 2>/dev/null | head -c 32)
printf "{\n  \"Key\": \"$new_key\"\n}" > $rsr_key_file