# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osal-base.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fosal-base.proto\x1a\x19google/protobuf/any.proto\"H\n\x0bOSALRequest\x12%\n\x07request\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x12\n\nbackground\x18\x02 \x01(\x08\"v\n\x0cOSALResponse\x12\x1d\n\x07outcome\x18\x01 \x01(\x0e\x32\x0c.OSALOutcome\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\x12\"\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\x12\r\n\x05jobID\x18\x04 \x01(\r\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t*\x81\x01\n\x0bOSALOutcome\x12\x08\n\x04NONE\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x13\n\x0fUNKNOWN_REQUEST\x10\x03\x12\x13\n\x0fPARAMETER_ERROR\x10\x04\x12\x08\n\x04\x42USY\x10\x05\x12\x11\n\rNO_BACKGROUND\x10\x06\x12\x0e\n\nPROCESSING\x10\x07\x42\x1f\xaa\x02\x1cPrivilegeSeparation.Messagesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osal_base_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\034PrivilegeSeparation.Messages'
  _OSALOUTCOME._serialized_start=281
  _OSALOUTCOME._serialized_end=410
  _OSALREQUEST._serialized_start=46
  _OSALREQUEST._serialized_end=118
  _OSALRESPONSE._serialized_start=120
  _OSALRESPONSE._serialized_end=238
  _KEYVALUE._serialized_start=240
  _KEYVALUE._serialized_end=278
# @@protoc_insertion_point(module_scope)
