#!/bin/sh

. /usr/lib/rlx-osal-plugin-addon/rlx-addon.inc.sh

PACKAGE_NAME=$1
PACKAGE_VERSION=$2
WORK_DIR=$3

starttime=`date -R`

install_addon "${PACKAGE_NAME}" "${WORK_DIR}"
retval=$?

if [ $retval -eq 0 ]; then
    success=1
else
    success=0
fi

log_history "$starttime;$PACKAGE_NAME;$PACKAGE_VERSION;install;$success"

exit $retval
