#!/bin/sh

WORK_DIR=$1

errlog=$WORK_DIR/rlx-upgrade.log
exec >> $errlog 2>&1
set -x

if [ -z "$WORK_DIR" ]; then
    echo "Usage: $0 WORK_DIR" >&2
    exit 1
fi

if [ -f "$WORK_DIR/archive/pre-upgrade.sh" ]; then
    . /usr/lib/rlx-osal/rlx-upgrade.inc.sh
    log_info "Executing pre-upgrade script ..."
    exec sh $WORK_DIR/archive/pre-upgrade.sh $WORK_DIR
fi
