Window.SetBackgroundTopColor(255, 255, 255);
Window.SetBackgroundBottomColor(255, 255, 255);

logo_orig.image = Image("roche-sting.png");
logo.scale_factor = Window.GetHeight() / logo_orig.image.GetHeight();
logo.image = logo_orig.image.Scale(logo_orig.image.GetWidth() * logo.scale_factor, logo_orig.image.GetHeight() * logo.scale_factor);
logo.sprite = Sprite(logo.image);
logo.opacity_angle = 0;

fun refresh_callback () {
    if (status == "normal") {
        logo.sprite.SetX (Window.GetX() + Window.GetWidth()  / 2 - logo.image.GetWidth()  / 2);
        logo.sprite.SetY (Window.GetY() + Window.GetHeight() / 2 - logo.image.GetHeight() / 2);
        logo.sprite.SetOpacity (1);
    }
    else {
        logo.sprite.SetX (0);
        logo.sprite.SetY (0);
        logo.sprite.SetOpacity (1);
    }
}

Plymouth.SetRefreshFunction (refresh_callback);

#----------------------------------------- Dialogue --------------------------------

status = "normal";

fun dialog_setup() {
    local.box;
    local.lock;
    local.entry;

    box.image = Image("box.png");
    lock.image = Image("lock.png");
    entry.image = Image("entry.png");

    ox.sprite = Sprite(box.image);
    box.x = Window.GetX() + Window.GetWidth()  / 2 - box.image.GetWidth ()/2;
    box.y = Window.GetY() + Window.GetHeight() / 2 - box.image.GetHeight()/2;
    box.z = 10000;
    box.sprite.SetPosition(box.x, box.y, box.z);

    lock.sprite = Sprite(lock.image);
    lock.x = box.x + box.image.GetWidth()/2 - (lock.image.GetWidth() + entry.image.GetWidth()) / 2;
    lock.y = box.y + box.image.GetHeight()/2 - lock.image.GetHeight()/2;
    lock.z = box.z + 1;
    lock.sprite.SetPosition(lock.x, lock.y, lock.z);

    entry.sprite = Sprite(entry.image);
    entry.x = lock.x + lock.image.GetWidth();
    entry.y = box.y + box.image.GetHeight()/2 - entry.image.GetHeight()/2;
    entry.z = box.z + 1;
    entry.sprite.SetPosition(entry.x, entry.y, entry.z);

    global.dialog.box = box;
    global.dialog.lock = lock;
    global.dialog.entry = entry;
    global.dialog.bullet_image = Image("bullet.png");
    dialog_opacity (1);
}

fun dialog_opacity(opacity) {
    dialog.box.sprite.SetOpacity (opacity);
    dialog.lock.sprite.SetOpacity (opacity);
    dialog.entry.sprite.SetOpacity (opacity);
    for (index = 0; dialog.bullet[index]; index++) {
        dialog.bullet[index].sprite.SetOpacity(opacity);
    }
}

fun display_normal_callback () {
    global.status = "normal";
    if (global.dialog)
      dialog_opacity (0);
}

fun display_password_callback (prompt, bullets) {
    global.status = "password";
    if (!global.dialog)
      dialog_setup();
    else
      dialog_opacity(1);
    for (index = 0; dialog.bullet[index] || index < bullets; index++) {
        if (!dialog.bullet[index]) {
            dialog.bullet[index].sprite = Sprite(dialog.bullet_image);
            dialog.bullet[index].x = dialog.entry.x + index * dialog.bullet_image.GetWidth();
            dialog.bullet[index].y = dialog.entry.y + dialog.entry.image.GetHeight() / 2 - dialog.bullet_image.GetHeight() / 2;
            dialog.bullet[index].z = dialog.entry.z + 1;
            dialog.bullet[index].sprite.SetPosition(dialog.bullet[index].x, dialog.bullet[index].y, dialog.bullet[index].z);
        }
        if (index < bullets)
          dialog.bullet[index].sprite.SetOpacity(1);
        else
          dialog.bullet[index].sprite.SetOpacity(0);
    }
}

Plymouth.SetDisplayNormalFunction(display_normal_callback);
Plymouth.SetDisplayPasswordFunction(display_password_callback);

#----------------------------------------- Progress Bar --------------------------------

progress_box.image = Image("progress_box.png");
progress_box.sprite = Sprite(progress_box.image);

progress_box.x = Window.GetX() + Window.GetWidth() / 2 - progress_box.image.GetWidth() / 2;
progress_box.y = Window.GetY() + Window.GetHeight() * 0.3 - progress_box.image.GetHeight() / 2;
progress_box.sprite.SetPosition(progress_box.x, progress_box.y, 0);

progress_bar.original_image = Image("progress_bar.png");
progress_bar.sprite = Sprite();

progress_bar.x = Window.GetX() + Window.GetWidth()  / 2 -        progress_bar.original_image.GetWidth() / 2;
progress_bar.y = Window.GetY() + Window.GetHeight() * 0.3  - progress_box.image.GetHeight() / 2 + (progress_box.image.GetHeight() - progress_bar.original_image.GetHeight()) / 2;
progress_bar.sprite.SetPosition(progress_bar.x, progress_bar.y, 1);

fun progress_callback (duration, progress) {
    if (progress_bar.image.GetWidth () != Math.Int (progress_bar.original_image.GetWidth () * progress)) {
        progress_bar.image = progress_bar.original_image.Scale(progress_bar.original_image.GetWidth(progress_bar.original_image) * progress, progress_bar.original_image.GetHeight());
        progress_bar.sprite.SetImage (progress_bar.image);
    }
}

fun progress_upgrade_callback (progress) {
    if (progress_bar.image.GetWidth () != Math.Int (progress_bar.original_image.GetWidth () * progress/100.0)) {
        progress_bar.image = progress_bar.original_image.Scale(Math.Int(progress_bar.original_image.GetWidth(progress_bar.original_image) * progress/100.0), progress_bar.original_image.GetHeight());
        progress_bar.sprite.SetImage (progress_bar.image);
    }
}

if (Plymouth.GetMode() == "boot" || Plymouth.GetMode() == "shutdown" || Plymouth.GetMode() == "reboot") {
    Plymouth.SetBootProgressFunction(progress_callback);
}
if (Plymouth.GetMode() == "updates" || Plymouth.GetMode() == "system-upgrade" || Plymouth.GetMode() == "firmware-upgrade") {
    Plymouth.SetSystemUpdateFunction(progress_upgrade_callback);
}

#----------------------------------------- Quit --------------------------------

fun quit_callback () {
  logo.sprite.SetOpacity (1);
}

Plymouth.SetQuitFunction(quit_callback);

#----------------------------------------- Message & Status Helper -------------

FancyString = String;

FancyString.Length = fun () {
  index = 0;
  while(CharAt(index)) index++;
  return index;
};

FancyString.FilterByPrefix = fun (prefix) {
  fancy_prefix = FancyString(prefix);
  if (Length() < fancy_prefix.Length()) {
    return NULL;
  }
  match = SubString(0, fancy_prefix.Length());
  if (match != prefix) {
    return NULL;
  }
  return SubString(fancy_prefix.Length(), Length());
};

roche_tag = "[Roche] ";  // keep in sync with roche-rlx3-updater.init
roche_upgrade_tag = "[Roche-upgrade] ";

#----------------------------------------- Message --------------------------------

message_sprites = [];
message_sprite_count = 0;
message_sprite_y = progress_box.sprite.GetY() + 3 * progress_box.image.GetHeight();

fun display_message_callback (text) {
  filtered = FancyString(text).FilterByPrefix(roche_tag);
  if (filtered != NULL) {
    my_image = Image.Text(filtered, 0, 0, 0);
    message_sprite_x = Window.GetX() + Window.GetWidth()  / 2 - my_image.GetWidth()  / 2;
    message_sprites[message_sprite_count] = Sprite(my_image);
    message_sprites[message_sprite_count].SetPosition(message_sprite_x, message_sprite_y, 10000);
    message_sprites[message_sprite_count].text = filtered;
    message_sprite_count++;
    message_sprite_y += my_image.GetHeight();
  }
  filtered_upgrade = FancyString(text).FilterByPrefix(roche_upgrade_tag);
  if (filtered_upgrade != NULL) {
    my_image = Image.Text(filtered_upgrade, 0, 0, 0);
    message_sprite_x = Window.GetX() + Math.Int (Window.GetWidth() * 0.3 );
    message_sprites[message_sprite_count] = Sprite(my_image);
    message_sprites[message_sprite_count].SetPosition(message_sprite_x, message_sprite_y, 10000);
    message_sprites[message_sprite_count].text = filtered_upgrade;
    message_sprite_count++;
    message_sprite_y += my_image.GetHeight();
  }
}

fun hide_message_callback (text) {
  for (i = 0; i < message_sprite_count; i++) {
      if (message_sprites[i].text == text)
        message_sprites[i] = NULL;
  }
}

Plymouth.SetDisplayMessageFunction (display_message_callback);
Plymouth.SetHideMessageFunction (hide_message_callback);

#----------------------------------------- Status --------------------------------

status_sprites = [];
status_sprite_count = 0;

fun display_status_callback (text) {
  filtered = FancyString(text).FilterByPrefix(roche_tag);
  if (filtered != NULL) {
    my_image = Image.Text(filtered, 0, 0, 0);
    status_sprites[status_sprite_count] = Sprite(my_image);
    status_sprites[status_sprite_count].SetPosition(10, message_sprite_y, 10000);
    status_sprites[status_sprite_count].text = filtered;
    status_sprite_count++;
    message_sprite_y += my_image.GetHeight();
  }
}

Plymouth.SetUpdateStatusFunction (display_status_callback);

