#!/bin/bash
#
# reject access = 0
# allow access  = 1

# VARIABLES
PID_FILE="/var/run/rlx-remote-access/sh/sessions/$$"
ALLOW_FILE="/var/lib/rlx-remote-access/sh/allow"
BOLD=$(tput bold 2>/dev/null || echo "")
RED=$(tput setaf 1 2>/dev/null || echo "")
GREEN=$(tput setaf 2 2>/dev/null || echo "")
RESET=$(tput sgr0 2>/dev/null || echo "")

function send_login_event() {
  /usr/bin/python3 -c "from rlx_osal import OSAL;OSAL().ShellAccessLogin()"
}

function send_logout_event() {
  /usr/bin/python3 -c "from rlx_osal import OSAL;OSAL().ShellAccessLogout()"
}

function cleanup() {
  rm $PID_FILE &>/dev/null
  if [ -n "$TERM" ] && ! [[ $TERM =~ dumb ]]; then
    # shell is interactive
    echo "Bye!"
  fi
  send_logout_event
}

trap 'cleanup' EXIT

touch $PID_FILE || exit 1

if [ -n "$*" ]; then
  if [ ! -f $ALLOW_FILE ] || [ -f $ALLOW_FILE ] && [ "$(<$ALLOW_FILE)" = 0 ]; then
    exit
  fi
  send_login_event
  /bin/sh "$@"
  exit
fi

if [ -z "$SSH_TTY" ] && [ -z "$SSH_CLIENT" ]; then
  # Direct access from console
  send_login_event
  /bin/bash
else
  echo
  echo -e "${GREEN}${BOLD} Welcome to the RLX Auth Shell${RESET}"
  echo -e "${GREEN}${BOLD}===================================${RESET}"
  echo

  /opt/roche/sbin/rlx-authsh-req-acs

  case "$?" in
  0)
    echo -e "Shell access ${GREEN}${BOLD}granted${RESET}\n"
    send_login_event
    /bin/bash
    ;;
  1)
    echo -e "Shell access ${RED}${BOLD}rejected${RESET}\n"
    ;;
  *)
    echo -e "${RED}Error (code $?)${RESET}\n"
    ;;
  esac
fi
