[directories]
systemreport = /opt/roche/var/lib/mollab/shared/system-reports
screenshot   = /opt/roche/var/lib/mollab/shared/screenshots

[applogs]
directory = /opt/roche/var/lib/mollab/shared/logs

[shell]
user = fsr
