#!/bin/sh

marker_file=/opt/roche/var/lib/mollab/private/instrument/.installDone

if [ ! -f "$marker_file" ]; then

  echo "First startup after an installation or upgrade, running installation scripts..."

  # use subshell to avoid changing the current directory, and we want to change it to reduce the path length in the logs
  (
    cd /opt/roche/lib/mollab/private/instrument &&
    run-parts --verbose install.d
  )

  touch "$marker_file"
  echo "Done running installation scripts"
fi