# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin-addon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import osal_base_pb2 as osal__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12plugin-addon.proto\x1a\x0fosal-base.proto\"\x1b\n\x19GetInstalledAddonPackages\"o\n\x0c\x41\x64\x64onPackage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x18\n\x10long_description\x18\x04 \x01(\t\x12\x11\n\tinstalled\x18\x05 \x01(\x08\"0\n\rAddonPackages\x12\x1f\n\x08packages\x18\x01 \x03(\x0b\x32\r.AddonPackage\" \n\x10GetAddonPackages\x12\x0c\n\x04path\x18\x01 \x01(\t\"4\n\x13InstallAddonPackage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"3\n\x12RemoveAddonPackage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_addon_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETINSTALLEDADDONPACKAGES._serialized_start=39
  _GETINSTALLEDADDONPACKAGES._serialized_end=66
  _ADDONPACKAGE._serialized_start=68
  _ADDONPACKAGE._serialized_end=179
  _ADDONPACKAGES._serialized_start=181
  _ADDONPACKAGES._serialized_end=229
  _GETADDONPACKAGES._serialized_start=231
  _GETADDONPACKAGES._serialized_end=263
  _INSTALLADDONPACKAGE._serialized_start=265
  _INSTALLADDONPACKAGE._serialized_end=317
  _REMOVEADDONPACKAGE._serialized_start=319
  _REMOVEADDONPACKAGE._serialized_end=370
# @@protoc_insertion_point(module_scope)
