# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin-integrity-check.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import osal_base_pb2 as osal__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cplugin-integrity-check.proto\x1a\x0fosal-base.proto\"\x18\n\x16\x43heckSoftwareIntegrity\"K\n\x11SoftwareIntegrity\x12\x0e\n\x06passed\x18\x01 \x01(\x08\x12\x14\n\x0c\x63hangedFiles\x18\x02 \x03(\t\x12\x10\n\x08messages\x18\x07 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_integrity_check_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKSOFTWAREINTEGRITY._serialized_start=49
  _CHECKSOFTWAREINTEGRITY._serialized_end=73
  _SOFTWAREINTEGRITY._serialized_start=75
  _SOFTWAREINTEGRITY._serialized_end=150
# @@protoc_insertion_point(module_scope)
