# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin-remote-screen.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import osal_base_pb2 as osal__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aplugin-remote-screen.proto\x1a\x0fosal-base.proto\"%\n\x13RequestRemoteScreen\x12\x0e\n\x06userID\x18\x01 \x01(\t\"\'\n\x15RemoteScreenRequested\x12\x0e\n\x06userID\x18\x01 \x01(\t\"#\n\x11StartRemoteScreen\x12\x0e\n\x06userID\x18\x01 \x01(\t\"%\n\x13RemoteScreenStarted\x12\x0e\n\x06userID\x18\x01 \x01(\t\"\"\n\x10StopRemoteScreen\x12\x0e\n\x06userID\x18\x01 \x01(\t\"%\n\x13RemoteScreenStopped\x12\x0e\n\x06userid\x18\x01 \x01(\t\"\x17\n\x15GetRemoteScreenStatus\"%\n\x12RemoteScreenStatus\x12\x0f\n\x07running\x18\x01 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_remote_screen_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTREMOTESCREEN._serialized_start=47
  _REQUESTREMOTESCREEN._serialized_end=84
  _REMOTESCREENREQUESTED._serialized_start=86
  _REMOTESCREENREQUESTED._serialized_end=125
  _STARTREMOTESCREEN._serialized_start=127
  _STARTREMOTESCREEN._serialized_end=162
  _REMOTESCREENSTARTED._serialized_start=164
  _REMOTESCREENSTARTED._serialized_end=201
  _STOPREMOTESCREEN._serialized_start=203
  _STOPREMOTESCREEN._serialized_end=237
  _REMOTESCREENSTOPPED._serialized_start=239
  _REMOTESCREENSTOPPED._serialized_end=276
  _GETREMOTESCREENSTATUS._serialized_start=278
  _GETREMOTESCREENSTATUS._serialized_end=301
  _REMOTESCREENSTATUS._serialized_start=303
  _REMOTESCREENSTATUS._serialized_end=340
# @@protoc_insertion_point(module_scope)
