# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin-screenshot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import osal_base_pb2 as osal__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17plugin-screenshot.proto\x1a\x0fosal-base.proto\"\"\n\x0eTakeScreenshot\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"K\n\x13TakeScreenshotToUSB\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tdirectory\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65vname\x18\x03 \x01(\t\"1\n\nScreenshot\x12\x11\n\tdirectory\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_screenshot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TAKESCREENSHOT._serialized_start=44
  _TAKESCREENSHOT._serialized_end=78
  _TAKESCREENSHOTTOUSB._serialized_start=80
  _TAKESCREENSHOTTOUSB._serialized_end=155
  _SCREENSHOT._serialized_start=157
  _SCREENSHOT._serialized_end=206
# @@protoc_insertion_point(module_scope)
