# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin-system-snapshots.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import osal_base_pb2 as osal__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dplugin-system-snapshots.proto\x1a\x0fosal-base.proto\"\x0e\n\x0c\x46\x61\x63toryReset\"3\n\x14\x46\x61\x63torySystemVersion\x12\x1b\n\x13snapshotPercentages\x18\x01 \x03(\x01\"\x19\n\x17GetFactorySystemVersion\"\'\n\x13RemoveSystemVersion\x12\x10\n\x08systemID\x18\x01 \x01(\r\"*\n\x16SetActiveSystemVersion\x12\x10\n\x08systemID\x18\x01 \x01(\r\"d\n\rSystemVersion\x12\x10\n\x08systemID\x18\x01 \x01(\r\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x13\n\x0binstallDate\x18\x03 \x01(\t\x12\x1b\n\x13snapshotPercentages\x18\x04 \x03(\x01\"5\n\x11SystemVersionList\x12 \n\x08versions\x18\x01 \x03(\x0b\x32\x0e.SystemVersion\"\x16\n\x14GetSystemVersionList\"d\n\x0cSnapshotInfo\x12\x1a\n\x12snapshotsSupported\x18\x01 \x01(\x08\x12\x1d\n\x15snapshottingAvailable\x18\x02 \x01(\x08\x12\x19\n\x11\x66reeSnapshotSpace\x18\x03 \x01(\x04\"\x11\n\x0fGetSnapshotInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_system_snapshots_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FACTORYRESET._serialized_start=50
  _FACTORYRESET._serialized_end=64
  _FACTORYSYSTEMVERSION._serialized_start=66
  _FACTORYSYSTEMVERSION._serialized_end=117
  _GETFACTORYSYSTEMVERSION._serialized_start=119
  _GETFACTORYSYSTEMVERSION._serialized_end=144
  _REMOVESYSTEMVERSION._serialized_start=146
  _REMOVESYSTEMVERSION._serialized_end=185
  _SETACTIVESYSTEMVERSION._serialized_start=187
  _SETACTIVESYSTEMVERSION._serialized_end=229
  _SYSTEMVERSION._serialized_start=231
  _SYSTEMVERSION._serialized_end=331
  _SYSTEMVERSIONLIST._serialized_start=333
  _SYSTEMVERSIONLIST._serialized_end=386
  _GETSYSTEMVERSIONLIST._serialized_start=388
  _GETSYSTEMVERSIONLIST._serialized_end=410
  _SNAPSHOTINFO._serialized_start=412
  _SNAPSHOTINFO._serialized_end=512
  _GETSNAPSHOTINFO._serialized_start=514
  _GETSNAPSHOTINFO._serialized_end=531
# @@protoc_insertion_point(module_scope)
