# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin-usb-storage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import osal_base_pb2 as osal__base__pb2
import osal_pb2 as osal__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18plugin-usb-storage.proto\x1a\x0fosal-base.proto\x1a\nosal.proto\"\x13\n\x11GetUSBStorageList\".\n\x0eUSBStorageList\x12\x1c\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x0b.USBStorage\"1\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05isDir\x18\x02 \x01(\x08\x12\x0c\n\x04size\x18\x03 \x01(\x04\"\'\n\x0fUSBStorageFiles\x12\x14\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x05.File\"8\n\x12GetUSBStorageFiles\x12\x0f\n\x07\x64\x65vname\x18\x01 \x01(\t\x12\x11\n\tdirectory\x18\x02 \x01(\t\"&\n\x14\x46ileExistsUSBStorage\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\":\n\x19\x43heckFileExistsUSBStorage\x12\x0f\n\x07\x64\x65vname\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"T\n\x15\x43opyFilesToUSBStorage\x12\x0f\n\x07\x64\x65vname\x18\x01 \x01(\t\x12\x13\n\x0bsourceFiles\x18\x02 \x03(\t\x12\x15\n\rdestDirectory\x18\x03 \x01(\t\"b\n\x12\x43opyFromUSBStorage\x12\x0f\n\x07\x64\x65vname\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x15\n\rdestDirectory\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x65stFilename\x18\x04 \x01(\t\"2\n\x13USBStorageDiskSpace\x12\r\n\x05total\x18\x01 \x01(\x04\x12\x0c\n\x04\x66ree\x18\x02 \x01(\x04\")\n\x16GetUSBStorageDiskSpace\x12\x0f\n\x07\x64\x65vname\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_usb_storage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETUSBSTORAGELIST._serialized_start=57
  _GETUSBSTORAGELIST._serialized_end=76
  _USBSTORAGELIST._serialized_start=78
  _USBSTORAGELIST._serialized_end=124
  _FILE._serialized_start=126
  _FILE._serialized_end=175
  _USBSTORAGEFILES._serialized_start=177
  _USBSTORAGEFILES._serialized_end=216
  _GETUSBSTORAGEFILES._serialized_start=218
  _GETUSBSTORAGEFILES._serialized_end=274
  _FILEEXISTSUSBSTORAGE._serialized_start=276
  _FILEEXISTSUSBSTORAGE._serialized_end=314
  _CHECKFILEEXISTSUSBSTORAGE._serialized_start=316
  _CHECKFILEEXISTSUSBSTORAGE._serialized_end=374
  _COPYFILESTOUSBSTORAGE._serialized_start=376
  _COPYFILESTOUSBSTORAGE._serialized_end=460
  _COPYFROMUSBSTORAGE._serialized_start=462
  _COPYFROMUSBSTORAGE._serialized_end=560
  _USBSTORAGEDISKSPACE._serialized_start=562
  _USBSTORAGEDISKSPACE._serialized_end=612
  _GETUSBSTORAGEDISKSPACE._serialized_start=614
  _GETUSBSTORAGEDISKSPACE._serialized_end=655
# @@protoc_insertion_point(module_scope)
