# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin-webshell.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import osal_base_pb2 as osal__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15plugin-webshell.proto\x1a\x0fosal-base.proto\"7\n\nStartShell\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04\x63ols\x18\x02 \x01(\r\x12\x0c\n\x04rows\x18\x03 \x01(\r\"\x1b\n\x0bShellOutput\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1a\n\tStopShell\x12\r\n\x05topic\x18\x01 \x01(\t\"\'\n\tSendShell\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"8\n\x0bResizeShell\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04\x63ols\x18\x02 \x01(\r\x12\x0c\n\x04rows\x18\x03 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_webshell_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTSHELL._serialized_start=42
  _STARTSHELL._serialized_end=97
  _SHELLOUTPUT._serialized_start=99
  _SHELLOUTPUT._serialized_end=126
  _STOPSHELL._serialized_start=128
  _STOPSHELL._serialized_end=154
  _SENDSHELL._serialized_start=156
  _SENDSHELL._serialized_end=195
  _RESIZESHELL._serialized_start=197
  _RESIZESHELL._serialized_end=253
# @@protoc_insertion_point(module_scope)
